#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  ./docker/scripts/bootstrap-django.sh ENV PROJECT_NAME \
    [--requirements requirements.txt] \
    [--seed-command COMMAND] \
    [--collectstatic] \
    [--skip-sync] \
    [--no-start-service]

Examples:
  ./docker/scripts/bootstrap-django.sh dev demo_fullstack

  ./docker/scripts/bootstrap-django.sh \
    dev demo_fullstack \
    --seed-command seed_beefont

  ./docker/scripts/bootstrap-django.sh \
    dev demo_fullstack \
    --collectstatic
EOF
}

require_cmd() {
  local cmd="${1:-}"
  if ! command -v "${cmd}" >/dev/null 2>&1; then
    echo "Missing required command: ${cmd}" >&2
    exit 1
  fi
}

require_file() {
  local file="${1:-}"
  if [[ -z "${file}" || ! -f "${file}" ]]; then
    echo "Missing file: ${file}" >&2
    exit 1
  fi
}

read_env_value_from_file() {
  local file="${1:-}"
  local key="${2:-}"
  local line=""

  if [[ -z "${file}" || -z "${key}" || ! -f "${file}" ]]; then
    return 0
  fi

  line="$(grep -E "^${key}=" "${file}" | tail -n 1 || true)"
  if [[ -z "${line}" ]]; then
    return 0
  fi

  printf '%s\n' "${line#*=}"
}

resolve_host_path() {
  local raw_path="${1:-}"

  if [[ -z "${raw_path}" ]]; then
    return 0
  fi

  case "${raw_path}" in
    /*)
      printf '%s\n' "${raw_path}"
      ;;
    ./*)
      printf '%s\n' "${DOCKER_DIR}/${raw_path#./}"
      ;;
    *)
      printf '%s\n' "${REPO_ROOT}/${raw_path}"
      ;;
  esac
}

extract_mount_source() {
  local mount_value="${1:-}"

  if [[ -z "${mount_value}" ]]; then
    return 0
  fi

  printf '%s\n' "${mount_value%%:*}"
}

url_to_origin() {
  local raw_url="${1:-}"
  python3 - "${raw_url}" <<'PY'
import sys
from urllib.parse import urlsplit

raw = sys.argv[1] if len(sys.argv) > 1 else ""
if not raw:
    print("")
    raise SystemExit(0)

u = urlsplit(raw)
if not u.scheme or not u.netloc:
    print("")
    raise SystemExit(0)

print(f"{u.scheme}://{u.netloc}")
PY
}

url_to_host() {
  local raw_url="${1:-}"
  python3 - "${raw_url}" <<'PY'
import sys
from urllib.parse import urlsplit

raw = sys.argv[1] if len(sys.argv) > 1 else ""
if not raw:
    print("")
    raise SystemExit(0)

u = urlsplit(raw)
print(u.hostname or "")
PY
}

run_django_once() {
  local shell_cmd="${1:-}"
  if [[ -z "${shell_cmd}" ]]; then
    echo "Missing Django shell command." >&2
    exit 1
  fi

  "${COMPOSE_CMD[@]}" run --rm --no-deps -T "${DJANGO_SERVICE}" sh -lc "${shell_cmd}"
}

wait_for_postgres() {
  local tries=60

  echo "Waiting for PostgreSQL health..."
  for _ in $(seq 1 "${tries}"); do
    if "${COMPOSE_CMD[@]}" exec -T "${DJANGO_DB_SERVICE}" sh -lc 'pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"' >/dev/null 2>&1; then
      echo "PostgreSQL is ready."
      return 0
    fi
    sleep 2
  done

  echo "PostgreSQL did not become ready in time." >&2
  return 1
}

write_runtime_env_file() {
  local template_file=""
  local debug_value=""
  local wp_origin=""
  local django_origin=""
  local wp_host=""
  local django_host=""
  local allowed_hosts=""
  local django_base_url=""
  local database_url=""

  for candidate in \
    "${DATA_DJANGO_DIR}/env.${ENV_NAME}.example" \
    "${DATA_DJANGO_DIR}/.env.${ENV_NAME}.example"
  do
    if [[ -f "${candidate}" ]]; then
      template_file="${candidate}"
      break
    fi
  done

  mkdir -p "$(dirname "${RUNTIME_DJANGO_ENV_FILE}")"

  if [[ -n "${template_file}" ]]; then
    cp "${template_file}" "${RUNTIME_DJANGO_ENV_FILE}"
  else
    : > "${RUNTIME_DJANGO_ENV_FILE}"
  fi

  if [[ "${ENV_NAME}" == "dev" ]]; then
    debug_value="True"
    django_base_url="http://localhost:${DJANGO_PORT}"
  else
    debug_value="False"
    django_base_url="http://127.0.0.1:${DJANGO_PORT}"
  fi

  wp_origin="$(url_to_origin "${SITE_URL}")"
  django_origin="$(url_to_origin "${django_base_url}")"
  wp_host="$(url_to_host "${SITE_URL}")"
  django_host="$(url_to_host "${django_base_url}")"

  allowed_hosts="localhost,127.0.0.1,${DJANGO_SERVICE}"
  if [[ -n "${wp_host}" ]]; then
    allowed_hosts="${allowed_hosts},${wp_host}"
  fi
  if [[ -n "${django_host}" ]]; then
    allowed_hosts="${allowed_hosts},${django_host}"
  fi

  database_url="postgresql://${DJANGO_DB_USER}:${DJANGO_DB_PASSWORD}@${DJANGO_DB_SERVICE}:5432/${DJANGO_DB_NAME}"

  cat >> "${RUNTIME_DJANGO_ENV_FILE}" <<EOF

# Generated by bootstrap-django.sh (${ENV_NAME})
SECRET_KEY=${DJANGO_SECRET_KEY}
DEBUG=${debug_value}

DATABASE_HOST=${DJANGO_DB_SERVICE}
DATABASE_PORT=5432
DATABASE_URL=${database_url}

WP_BASE_URL=${SITE_URL}
DJANGO_BASE_URL=${django_base_url}

ALLOWED_HOSTS=${allowed_hosts}
CORS_ALLOWED_ORIGINS=${wp_origin},${django_origin}
CSRF_TRUSTED_ORIGINS=${wp_origin},${django_origin}

MEDIA_URL=/media/
MEDIA_ROOT=/django/media
BEEFONT_MEDIA_ROOT=/django/media/beefont
BEEFONT_BASE_URL=/api/beefont

STATIC_URL=/static/
STATIC_ROOT=/django/staticfiles

DEFAULT_USER_PASSWORD=DjangoPwd
BYPASS_MEDIA=0

SESSION_COOKIE_SAMESITE=Lax
CSRF_COOKIE_SAMESITE=Lax
SESSION_COOKIE_SECURE=False
CSRF_COOKIE_SECURE=False
EOF

  chmod 600 "${RUNTIME_DJANGO_ENV_FILE}"
}

ENV_NAME="${1:-}"
PROJECT_NAME="${2:-}"

if [[ -z "${ENV_NAME}" || -z "${PROJECT_NAME}" ]]; then
  usage
  exit 1
fi

shift 2

REQUIREMENTS_FILE="requirements.txt"
SEED_COMMAND=""
COLLECTSTATIC="false"
SYNC_RUNTIME="true"
START_SERVICE="true"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --requirements)
      REQUIREMENTS_FILE="${2:-}"
      shift 2
      ;;
    --seed-command)
      SEED_COMMAND="${2:-}"
      shift 2
      ;;
    --collectstatic)
      COLLECTSTATIC="true"
      shift
      ;;
    --skip-sync)
      SYNC_RUNTIME="false"
      shift
      ;;
    --no-start-service)
      START_SERVICE="false"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ "${ENV_NAME}" != "dev" && "${ENV_NAME}" != "prod" ]]; then
  echo "ENV must be dev or prod." >&2
  exit 1
fi

if [[ ! "${PROJECT_NAME}" =~ ^[a-z0-9_]+$ ]]; then
  echo "Invalid project name: ${PROJECT_NAME}" >&2
  exit 1
fi

require_cmd docker
require_cmd jq
require_cmd rsync
require_cmd python3

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOCKER_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${DOCKER_DIR}/.." && pwd)"

WORLD_FILE="${REPO_ROOT}/data/world-list.json"
COMPOSE_FILE="${DOCKER_DIR}/compose.yaml"
DATA_DJANGO_DIR="${REPO_ROOT}/data/${PROJECT_NAME}/django"

if [[ "${ENV_NAME}" == "dev" ]]; then
  ENV_FILE="${DOCKER_DIR}/.env.dev"
else
  ENV_FILE="${DOCKER_DIR}/.env.prod"
fi

require_file "${WORLD_FILE}"
require_file "${COMPOSE_FILE}"
require_file "${ENV_FILE}"

PROJECT_JSON="$(
  jq -e --arg name "${PROJECT_NAME}" '
    (.projects // .)[] | select((.projectname // .name) == $name)
  ' "${WORLD_FILE}"
)"

PROJECT_TYPE="$(printf '%s\n' "${PROJECT_JSON}" | jq -r '.projecttype // empty')"
if [[ "${PROJECT_TYPE}" != "fullstack" ]]; then
  echo "Project ${PROJECT_NAME} is not a fullstack project." >&2
  exit 1
fi

DJANGO_SERVICE="$(printf '%s\n' "${PROJECT_JSON}" | jq -r '.compose.django_service // empty')"
DJANGO_DB_SERVICE="$(printf '%s\n' "${PROJECT_JSON}" | jq -r '.compose.django_db_service // empty')"

DJANGO_CODE_MOUNT_KEY="$(printf '%s\n' "${PROJECT_JSON}" | jq -r '.env.django_code_mount // empty')"
DJANGO_ENV_FILE_KEY="$(printf '%s\n' "${PROJECT_JSON}" | jq -r '.env.django_env_file // empty')"
DJANGO_PORT_KEY="$(printf '%s\n' "${PROJECT_JSON}" | jq -r '.env.django_port // empty')"
DJANGO_DB_NAME_KEY="$(printf '%s\n' "${PROJECT_JSON}" | jq -r '.env.django_db_name // empty')"
DJANGO_DB_USER_KEY="$(printf '%s\n' "${PROJECT_JSON}" | jq -r '.env.django_db_user // empty')"
DJANGO_DB_PASSWORD_KEY="$(printf '%s\n' "${PROJECT_JSON}" | jq -r '.env.django_db_password // empty')"
DJANGO_SECRET_KEY_KEY="$(printf '%s\n' "${PROJECT_JSON}" | jq -r '.env.django_secret_key // empty')"
SITE_URL_KEY="$(printf '%s\n' "${PROJECT_JSON}" | jq -r '.env.site_url // empty')"

WP_PORT_KEY="$(printf '%s\n' "${PROJECT_JSON}" | jq -r '.env.wp_port // .env.port // empty')"

if [[ -z "${DJANGO_SERVICE}" || -z "${DJANGO_DB_SERVICE}" ]]; then
  echo "Project ${PROJECT_NAME} is missing django_service or django_db_service in ${WORLD_FILE}." >&2
  exit 1
fi

if [[ -z "${DJANGO_CODE_MOUNT_KEY}" || -z "${DJANGO_ENV_FILE_KEY}" ]]; then
  echo "Project ${PROJECT_NAME} is missing django env mapping in ${WORLD_FILE}." >&2
  exit 1
fi

if [[ ! -d "${DATA_DJANGO_DIR}" ]]; then
  echo "Missing Django source directory: ${DATA_DJANGO_DIR}" >&2
  echo "Put delivered Django code there before bootstrapping." >&2
  exit 1
fi

if [[ ! -f "${DATA_DJANGO_DIR}/manage.py" ]]; then
  echo "Missing ${DATA_DJANGO_DIR}/manage.py" >&2
  echo "Expected the contents of a compatible Django project in data/${PROJECT_NAME}/django/." >&2
  exit 1
fi

if [[ ! -f "${DATA_DJANGO_DIR}/${REQUIREMENTS_FILE}" ]]; then
  echo "Missing ${DATA_DJANGO_DIR}/${REQUIREMENTS_FILE}" >&2
  exit 1
fi

DJANGO_CODE_MOUNT_VALUE="$(read_env_value_from_file "${ENV_FILE}" "${DJANGO_CODE_MOUNT_KEY}")"
DJANGO_ENV_FILE_VALUE="$(read_env_value_from_file "${ENV_FILE}" "${DJANGO_ENV_FILE_KEY}")"
DJANGO_PORT="$(read_env_value_from_file "${ENV_FILE}" "${DJANGO_PORT_KEY}")"
DJANGO_DB_NAME="$(read_env_value_from_file "${ENV_FILE}" "${DJANGO_DB_NAME_KEY}")"
DJANGO_DB_USER="$(read_env_value_from_file "${ENV_FILE}" "${DJANGO_DB_USER_KEY}")"
DJANGO_DB_PASSWORD="$(read_env_value_from_file "${ENV_FILE}" "${DJANGO_DB_PASSWORD_KEY}")"
DJANGO_SECRET_KEY="$(read_env_value_from_file "${ENV_FILE}" "${DJANGO_SECRET_KEY_KEY}")"
SITE_URL="$(read_env_value_from_file "${ENV_FILE}" "${SITE_URL_KEY}")"
WP_PORT="$(read_env_value_from_file "${ENV_FILE}" "${WP_PORT_KEY}")"

if [[ -z "${DJANGO_CODE_MOUNT_VALUE}" ]]; then
  echo "Missing ${DJANGO_CODE_MOUNT_KEY} in ${ENV_FILE}" >&2
  exit 1
fi

if [[ -z "${DJANGO_ENV_FILE_VALUE}" ]]; then
  echo "Missing ${DJANGO_ENV_FILE_KEY} in ${ENV_FILE}" >&2
  exit 1
fi

DJANGO_RUNTIME_DIR="$(resolve_host_path "$(extract_mount_source "${DJANGO_CODE_MOUNT_VALUE}")")"
RUNTIME_DJANGO_ENV_FILE="$(resolve_host_path "${DJANGO_ENV_FILE_VALUE}")"

if [[ -z "${DJANGO_RUNTIME_DIR}" || -z "${RUNTIME_DJANGO_ENV_FILE}" ]]; then
  echo "Failed to resolve Django runtime paths." >&2
  exit 1
fi

COMPOSE_CMD=(docker compose --env-file "${ENV_FILE}" -f "${COMPOSE_FILE}")

echo "Bootstrapping Django for project: ${PROJECT_NAME}"
echo "Environment: ${ENV_NAME}"
echo "Django DB service: ${DJANGO_DB_SERVICE}"
echo "Django service: ${DJANGO_SERVICE}"
echo "Data source: ${DATA_DJANGO_DIR}"
echo "Runtime target: ${DJANGO_RUNTIME_DIR}"
echo "Runtime env file: ${RUNTIME_DJANGO_ENV_FILE}"

mkdir -p "${DJANGO_RUNTIME_DIR}"

if [[ "${SYNC_RUNTIME}" == "true" ]]; then
  echo "Stopping Django service before sync..."
  "${COMPOSE_CMD[@]}" stop "${DJANGO_SERVICE}" >/dev/null 2>&1 || true

  echo "Syncing data/${PROJECT_NAME}/django -> $(basename "${DJANGO_RUNTIME_DIR}") ..."
  rsync -av --delete \
    --exclude '.git/' \
    --exclude '.venv/' \
    --exclude '__pycache__/' \
    --exclude '.pytest_cache/' \
    --exclude '.coverage' \
    --exclude '.env' \
    --exclude '.env.dev' \
    --exclude '.env.prod' \
    --exclude '*.pyc' \
    --exclude '*.pyo' \
    --exclude '*.pyd' \
    "${DATA_DJANGO_DIR}/" "${DJANGO_RUNTIME_DIR}/"
else
  echo "Skipping runtime sync."
fi

if [[ ! -f "${DJANGO_RUNTIME_DIR}/manage.py" ]]; then
  echo "Missing ${DJANGO_RUNTIME_DIR}/manage.py after sync." >&2
  exit 1
fi

echo "Writing Django runtime env file..."
write_runtime_env_file

echo "Starting Django database..."
"${COMPOSE_CMD[@]}" up -d "${DJANGO_DB_SERVICE}"

wait_for_postgres

echo "Checking Django project inside container..."
if ! run_django_once 'test -f /django/manage.py'; then
  echo "Missing /django/manage.py inside container." >&2
  exit 1
fi

if ! run_django_once "test -f /django/${REQUIREMENTS_FILE}"; then
  echo "Missing /django/${REQUIREMENTS_FILE} inside container." >&2
  exit 1
fi

echo "Creating/updating Django virtualenv..."
run_django_once "
  set -e
  cd /django
  python -m venv .venv
  ./.venv/bin/python -m pip install --upgrade pip
  ./.venv/bin/pip install -r ${REQUIREMENTS_FILE}
"

echo "Running Django migrations..."
run_django_once '
  set -e
  cd /django
  ./.venv/bin/python manage.py migrate
'

if [[ "${COLLECTSTATIC}" == "true" ]]; then
  echo "Running collectstatic..."
  run_django_once '
    set -e
    cd /django
    ./.venv/bin/python manage.py collectstatic --noinput
  '
fi

if [[ -n "${SEED_COMMAND}" ]]; then
  echo "Running seed command: ${SEED_COMMAND}"
  run_django_once "
    set -e
    cd /django
    ./.venv/bin/python manage.py ${SEED_COMMAND}
  "
fi

if [[ "${START_SERVICE}" == "true" ]]; then
  echo "Starting Django service..."
  "${COMPOSE_CMD[@]}" up -d "${DJANGO_SERVICE}"
else
  echo "Django service start skipped."
fi

echo
echo "Django bootstrap completed for ${PROJECT_NAME}."
echo "Requirements file: ${REQUIREMENTS_FILE}"
echo "Runtime env file: ${RUNTIME_DJANGO_ENV_FILE}"
if [[ -n "${SEED_COMMAND}" ]]; then
  echo "Seed command executed: ${SEED_COMMAND}"
fi
if [[ "${COLLECTSTATIC}" == "true" ]]; then
  echo "collectstatic executed."
fi